# Generated by Django 4.1.7 on 2023-02-26 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgroupchats', '0002_room_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgroupchats.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='webgroupchats.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
    ]
