# Generated by Django 4.1.7 on 2023-03-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgroupchats', '0004_alter_room_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-create_time',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
