# Generated by Django 4.1.7 on 2023-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgroupchats', '0005_alter_message_options_alter_message_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('create_time',)},
        ),
        migrations.AddField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=0),
        ),
    ]
