# Generated by Django 4.1.7 on 2023-03-09 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgroupchats', '0006_alter_message_options_room_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='author',
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='room_member', through='webgroupchats.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgroupchats.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='room_author', through='webgroupchats.AuthorRoom', to=settings.AUTH_USER_MODEL),
        ),
    ]
