# Generated by Django 4.1.7 on 2023-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgroupchats', '0007_remove_room_author_alter_room_members_authorroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='private',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('common', 'common'), ('private', 'private'), ('tetatet', 'tetatet')], default='common', max_length=16),
        ),
    ]
