# Generated by Django 4.1.7 on 2023-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgroupchats', '0008_remove_room_private_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='label',
            field=models.CharField(default=models.CharField(max_length=64, unique=True), max_length=64),
        ),
    ]
